### ISSUE TITLE
Running locally

### ISSUE THREAD

**Issue by codeinabox** [berrysauce/ingredients#28]
I can't find any documentation for running it locally. Does one need a Deta Space developer account for this?

**Comment by berrysauce** [comment]
You can start the FastAPI server locally by running the main.py file and you can seperately start the SvelteKit app located in the ui Folder. Don't forget to install all required packages from the requirements.txt file.

**Comment by codeinabox** [comment]
Thank you, I'll raise a PR to update the docs with this information. I could create a Makefile for running locally if you fancy

**Comment by berrysauce** [comment]
Oh you might need a Deta account after all. Maybe the Deta CLI with local execution should work

**Comment by codeinabox** [comment]
Is it easy enough to request a Deta Space account or is there quite a bit of vetting?

**Comment by berrysauce** [comment]
I think you can just sign up at https://deta.space

**Comment by mbaraa** [comment]
@codeinabox you can remove every "deta" related thing, (caching and db) and the api will run locally with no problems whatsoever!

**Comment by berrysauce** [comment]
> > I think you can just sign up at https://deta.space
> 
> https://discord.com/channels/827546555200438332/831945258228908112/1280158814494261359
> 
> ![oops](https://private-user-images.githubusercontent.com/42690037/363724064-2c0a2227-d055-4372-9b24-5f005def61d3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2NTM3NDEsIm5iZiI6MTcyODY1MzQ0MSwicGF0aCI6Ii80MjY5MDAzNy8zNjM3MjQwNjQtMmMwYTIyMjctZDA1NS00MzcyLTliMjQtNWYwMDVkZWY2MWQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDExVDEzMzA0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIyNmYwNmIwNGVjM2IzNTgzMTVhNWY2MDJiMGYzZWEzOGQ4ZGJmN2IyMGY0NjQ3NjgzYzYxMjk0OTFmZjBhOGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.-MqkqIubZO2uL-4eQzCNsWLTS6hwW4UGKgwuXfEsUVE)

Thanks for mentioning that! I've finished moving the whole web app to Vercel now. I had to take out the ingredients stats for now, but I'll be re-implementing them later. That also means it's possible to run the frontend/backend locally without problems (for now 😅) @codeinabox
