### ISSUE TITLE
Fix error text background (multiline)

### ISSUE THREAD

**Issue by berrysauce** [berrysauce/ingredients#4]
Multiline errors might have a broken padding & background.

**Comment by md-abid-hussain** [comment]
as per my knowledge I think you are referring to this 
![Screenshot (5)](https://github.com/berrysauce/ingredients/assets/101964499/517f903f-00d3-4855-b9df-7c0295c0c275)

**Comment by berrysauce** [comment]
> as per my knowledge I think you are referring to this 
> 
> ![Screenshot (5)](https://github.com/berrysauce/ingredients/assets/101964499/517f903f-00d3-4855-b9df-7c0295c0c275)
> 
> 

Nope, but that's another instance 😂 I was referring to the actual scan errors, which in some cases, might be long and multiline which then messes up the `<span>` padding. I got that under control for now with shorter error messages.
