### ISSUE TITLE
Results disappearing

### ISSUE THREAD

**Issue by berrysauce** [berrysauce/ingredients#5]
When scanning "https://ingredients.berrysauce.me" the results disappear. No error is shown.

**Comment by berrysauce** [comment]
With "https://www.python-httpx.org/quickstart/#redirection-and-history" as well

**Comment by solomonshalom** [comment]
I think it's fixed, considering when I first did it for my site - it didn't work but it's working now so maybe it's fixed?

**Comment by berrysauce** [comment]
> I think it's fixed, considering when I first did it for my site - it didn't work but it's working now so maybe it's fixed?
> 
> 

Yeah, I thought it worked again too. If you made a successful request first and then made an unsuccessful request, it seems to just display the results from the first, successful one.

But thanks so much for trying it out! What are your thoughts?

**Comment by solomonshalom** [comment]
Ah, I see - interesting!

NW, I actually found the project pretty cool and I can see multiple ways it can helpful! It's so cool!

**Comment by solomonshalom** [comment]
I also wanted to know if you could I and my team for our [OS project](https://github.com/solomonshalom/The-Abyss)? Would love to know! :D

**Comment by berrysauce** [comment]
Awesome! Thanks for the feedback & for the invite. I'm preparing for Uni and my new job in the next weeks, maybe some time later! 😃

**Comment by solomonshalom** [comment]
> Awesome! Thanks for the feedback & for the invite. I'm preparing for Uni and my new job in the next weeks, maybe some time later! 😃

Sure! ATB w/ that :D

**Comment by berrysauce** [comment]
Closed with #12
